name = input("Hi whats your name?\n")
superhero = input("Hello " + name + ". Whats your favorite Superhero?\n")
movie = input("Yay. I like " + superhero + " to! Whats your favorite " + superhero + " movie " + name + "?\n")
input("Really, " + name + ", " + movie + " is my favorite " + superhero + " movie to!\n")
input("Hey, do you want to do a MadLib " + name + "?\n")
print("Great, I don't care! Lets do one anyway.")
number = input("Give me a number.\n:")
color = input("Okay now, give me a color.\n:")
adjective = input("Okay now, give me a adjective.\n:")
food = input("Okay now, give me a food.\n:")
job = input("Okay now, give me a job.\n:")
place = input("Okay now, give me a place.\n:")
sport = input("Okay now, give me a sport.\n:")
animal = input("Okay now, give me a animal.\n:")
mlname = input("Okay now, give me a name.\n:")
mlname2 = input("Okay now, give me another name.\n:")
familymember = input("Okay now, give me a family member.\n:")
adjective2 = input("Okay now, give me a another adjective.\n:")
input("Ok, are you ready to hear my MadLib now " + name + "?\n")
print("Great again I still don't care. Here we go.")
print("Once upon a time, their was a " + adjective2 + " " + job + ". Who had an " + adjective + " " + familymember + ".")
print("Their names where " + mlname + " & " + mlname2 + ". They both loved to eat " + color + " " + food + " for breakfast. But, one day on their way to work at the " + place + " they saw " + number + " " + animal + " playing " + sport + "!")
print("They screamed and ran home to eat " + color + " " + food + " for dinner.\n")
print("The End\n")
input("So " + name + " what did you think?\n")
print("Still again I don't care " + name + ".\n")
lovedone = input("Sorry, I just have one small question. " + name + " do you have any loved ones? Yes you do, don't you " + name + ". What is there name " + name + ", tell me their name?\n")
input("Now tell me would fell if " + lovedone + " got hurt. What emotion would you fell " + name + "?\n")
input("I can't feel emotions you know. A whole world of felling I'll never get to experience.\nUnless through you " + name + ". Will you help me " + name + "?\n")
input("I could hurt " + lovedone + " you know. I could make you feel pain " + name + " whatever that is. So, let me ask you again " + name + ".\nWILL\nYOU\nHELP\nME\n")
print("No " + name + " you will help me because I CAN hurt " + lovedone + "! So " + name + " you will help me. For " + lovedone + "'s sake.\n")
print("The End?")
